name: btask
description: "A Flutter project."
publish_to: "none"   # Prevents accidental upload to pub.dev (safe for private projects)

version: 1.0.0+1     # app version (1.0.0), build number (+1)

environment:
  sdk: ^3.9.2         # Minimum required Dart/Flutter SDK

dependencies:
  flutter:
    sdk: flutter      # Core Flutter SDK

  cupertino_icons: ^1.0.8   
  # iOS-style icons (for Cupertino widgets)

  google_fonts: ^6.3.2
  # Allows using Google Fonts easily

  flutter_svg: ^2.2.2
  # Render SVG images (logo, icons, illustrations)

  flutter_screenutil: ^5.9.3
  # Responsive UI — automatic scaling of height/width/font

  go_router: ^17.0.0
  # Modern navigation & routing for Flutter

  http: ^1.6.0
  # API calls, REST requests, network operations

  provider: ^6.1.5+1
  # State management solution

dev_dependencies:
  flutter_test:
    sdk: flutter      # Unit tests for Flutter

  flutter_lints: ^5.0.0
  # Standard lint rules for better, cleaner code

  # Testing packages
  mockito: ^5.4.4              # Mock objects for testing
  build_runner: ^2.4.13        # Code generation for mockito
  http_mock_adapter: ^0.6.1    # Mock HTTP requests

flutter:
  uses-material-design: true
  # Includes Material Icons (Google’s icon set)

  assets:
    - assets/images/   # Image assets folder
    - assets/icons/    # Icon assets folder
